Traceback (most recent call last):
  File "/home/gaon/nothing/nothing/auto.py", line 32, in <module>
    button.accept()
  File "/home/gaon/.local/lib/python3.6/site-packages/selenium/webdriver/common/alert.py", line 90, in accept
    self.driver.execute(Command.ACCEPT_ALERT)
  File "/home/gaon/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/gaon/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.18.0-17-generic x86_64)

